# Generated by Django 2.0.7 on 2018-07-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('media', models.FileField(upload_to='')),
                ('thumbnailcreated', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
